#!/usr/bin/env python3
import re, sys
ucd, out = sys.argv[1], sys.argv[2]

def rows(path, want=None):
    for line in open(path, encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        f = [x.strip() for x in line.split(";")]
        lo, _, hi = f[0].partition("..")
        yield int(lo, 16), int(hi or lo, 16), f[1:]

def version(path):
    m = re.search(r"-(\d+\.\d+\.\d+)\.txt", open(path, encoding="utf-8").readline())
    return m.group(1) if m else None

gbp = ucd + "/auxiliary/GraphemeBreakProperty.txt"
ver = version(gbp)
dcp_ver = version(ucd + "/DerivedCoreProperties.txt")
if not ver or ver != dcp_ver:
    sys.exit("the data files do not name one Unicode version: %s, %s" % (ver, dcp_ver))
emoji_head = "".join(open(ucd + "/emoji/emoji-data.txt", encoding="utf-8").readlines()[:20])
m = re.search(r"Version:? (\d+\.\d+)", emoji_head)
if not m or not ver.startswith(m.group(1) + "."):
    sys.exit("emoji-data.txt is not of Unicode %s (its header names %s)" % (ver, m.group(1) if m else "no version"))
classes = ["Other", "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator", "Prepend", "SpacingMark", "L", "V", "T", "LV", "LVT"]
gcb = [(lo, hi, f[0]) for lo, hi, f in rows(gbp) if f[0] not in ("LV", "LVT")]
for _, _, c in gcb:
    if c not in classes:
        sys.exit("a grapheme class this generator does not know: " + c)
pict = [(lo, hi) for lo, hi, f in rows(ucd + "/emoji/emoji-data.txt") if f[0] == "Extended_Pictographic"]
incb = [(lo, hi, f[1]) for lo, hi, f in rows(ucd + "/DerivedCoreProperties.txt") if f[0] == "InCB"]

def merge(r):
    r = sorted(r); m = []
    for x in r:
        if m and x[0] <= m[-1][1] + 1 and x[2:] == m[-1][2:]:
            m[-1] = (m[-1][0], max(m[-1][1], x[1])) + tuple(x[2:])
        else:
            if m and x[0] <= m[-1][1]:
                sys.exit("overlapping ranges at U+%04X" % x[0])
            m.append(tuple(x))
    return m

gcb, pict, incb = merge(gcb), merge([(a, b) for a, b in pict]), merge(incb)
go = lambda c: "gcb" + c.replace("_", "")
with open(out, "w", encoding="utf-8") as f:
    f.write("// Code generated by internal/ucd/gen.py from the Unicode Character Database %s; DO NOT EDIT.\n" % ver)
    f.write("// The data files are the Unicode Consortium's, under the Unicode License v3\n// (https://www.unicode.org/license.txt).\n\n")
    f.write("package tokenizer\n\n// graphemeUnicodeVersion is the version of the tables below.\nconst graphemeUnicodeVersion = %s\n\n" % ('"%s"' % ver))
    f.write("var graphemeBreakRanges = []graphemeRange{\n")
    for lo, hi, c in gcb:
        f.write("\t{0x%04X, 0x%04X, %s},\n" % (lo, hi, go(c)))
    f.write("}\n\nvar extendedPictographicRanges = []runeRange{\n")
    for lo, hi in pict:
        f.write("\t{0x%04X, 0x%04X},\n" % (lo, hi))
    f.write("}\n\nvar incbRanges = []graphemeRange{\n")
    for lo, hi, c in incb:
        f.write("\t{0x%04X, 0x%04X, incb%s},\n" % (lo, hi, c))
    f.write("}\n")
print("Unicode %s: %d grapheme ranges, %d pictographic ranges, %d conjunct ranges" % (ver, len(gcb), len(pict), len(incb)))
